import { motion } from "framer-motion";
import {
  ArrowRight,
  BarChart3,
  Bot,
  BrainCircuit,
  CalendarDays,
  Check,
  ChevronDown,
  CircleDollarSign,
  CreditCard,
  Database,
  Landmark,
  LockKeyhole,
  Menu,
  PieChart,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingDown,
  TrendingUp,
  WalletCards,
  X,
} from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { ThemeToggle } from "../components/ThemeToggle";
import bannerClaro from "../../banner.branco.png";
import bannerEscuro from "../../banner.preto.png";
import logo from "../../logo.png";

const reveal = {
  hidden: { opacity: 0, y: 22 },
  visible: { opacity: 1, y: 0 },
};

const steps = [
  ["01", "Registre suas receitas", "Adicione salário, comissões, freelas, rendimentos e qualquer outra entrada de dinheiro."],
  ["02", "Organize seus gastos", "Separe despesas fixas, recorrentes, parceladas e gastos esporádicos em poucos cliques."],
  ["03", "Cadastre seus cartões", "Controle limites, faturas, fechamentos, vencimentos, compras e parcelas de cada cartão."],
  ["04", "Entenda seu dinheiro", "Veja o disponível hoje e o que já está comprometido para os próximos meses."],
];

const questions = [
  "Tenho dinheiro suficiente até o próximo salário?",
  "Quanto do meu salário já está comprometido?",
  "Essa compra vai cair nesta fatura ou na próxima?",
  "Quanto estou gastando com coisas que nem percebo?",
  "Posso realmente comprar isso agora?",
  "Quanto vou ter disponível daqui a 3 meses?",
];

const faqs = [
  ["A Nuvexa é um banco?", "Não. A Nuvexa é uma plataforma de gestão e inteligência financeira pessoal. Não movimentamos o seu dinheiro."],
  ["Preciso conectar minha conta bancária?", "Não. Você pode começar registrando seus dados manualmente e manter o controle completo das informações."],
  ["Meus dados estão seguros?", "Sim. A plataforma utiliza autenticação segura e regras de acesso que mantêm os dados de cada conta isolados."],
  ["Posso cadastrar vários cartões?", "Sim. Cadastre os cartões que utiliza e acompanhe limite, fatura, fechamento, vencimento e parcelas."],
  ["A Nuvexa identifica compras parceladas?", "Sim. As parcelas entram no seu planejamento para que você saiba o impacto de cada compra nos próximos meses."],
  ["Consigo acompanhar contas futuras?", "Sim. Calendário, projeções e compromissos ajudam a visualizar o seu mês antes que ele aconteça."],
];

const securityFeatures = [
  { icon: LockKeyhole, title: "Criptografia", copy: "Proteção durante a transmissão dos dados." },
  { icon: ShieldCheck, title: "Proteção de dados", copy: "Acesso isolado por conta e regras de segurança." },
  { icon: Database, title: "Autenticação segura", copy: "Sua conta permanece sob seu controle." },
  { icon: Landmark, title: "LGPD", copy: "Privacidade como parte da experiência." },
];

const plans = [
  { name: "Nuvexa Free", description: "Para começar a organizar sua vida financeira.", features: ["Receitas e despesas", "Dashboard financeiro", "Calendário básico"] },
  { name: "Nuvexa Plus", description: "Para quem quer controle completo e recursos avançados.", features: ["Cartões e parcelamentos", "Projeções avançadas", "Insights financeiros"] },
  { name: "Nuvexa Pro", description: "Para usuários que querem inteligência financeira e recursos completos.", features: ["Nuvexa IA", "Score financeiro", "Planejamento completo"] },
];

function Section({ children, className = "", id }: { children: React.ReactNode; className?: string; id?: string }) {
  return <section className={`px-4 py-20 sm:px-6 lg:py-28 ${className}`} id={id}><div className="mx-auto w-full max-w-7xl">{children}</div></section>;
}

function SectionHeading({ eyebrow, title, description, align = "left" }: { eyebrow?: string; title: string; description?: string; align?: "left" | "center" }) {
  return <motion.div className={align === "center" ? "mx-auto max-w-3xl text-center" : "max-w-3xl"} initial="hidden" transition={{ duration: 0.45 }} viewport={{ once: true, amount: 0.25 }} whileInView="visible" variants={reveal}>
    {eyebrow ? <p className="mb-4 text-sm font-bold uppercase tracking-[0.16em] text-cyan-700 dark:text-cyan-300">{eyebrow}</p> : null}
    <h2 className="text-3xl font-bold leading-tight text-slate-950 sm:text-4xl lg:text-5xl dark:text-white">{title}</h2>
    {description ? <p className="mt-5 text-base leading-8 text-slate-600 sm:text-lg dark:text-slate-300">{description}</p> : null}
  </motion.div>;
}

function DemoDashboard() {
  return <motion.div animate={{ opacity: 1, y: 0 }} className="overflow-hidden rounded-2xl border border-slate-200 bg-white p-3 shadow-[0_28px_80px_-36px_rgba(15,23,42,0.45)] sm:p-5 dark:border-slate-700 dark:bg-slate-900" initial={{ opacity: 0, y: 22 }} transition={{ duration: 0.65, delay: 0.15 }}>
    <div className="mb-5 flex items-center justify-between border-b border-slate-100 pb-4 dark:border-slate-800"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-400">Visão geral</p><p className="mt-1 font-bold text-slate-900 dark:text-white">Agosto de 2026</p></div><div className="rounded-lg bg-cyan-50 px-3 py-2 text-xs font-bold text-cyan-700 dark:bg-cyan-400/10 dark:text-cyan-200">Atualizado agora</div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      {[['Saldo disponível', 'R$ 3.840,00', 'text-cyan-700'], ['Receitas do mês', 'R$ 5.200,00', 'text-emerald-600'], ['Gastos', 'R$ 2.410,00', 'text-rose-600'], ['Comprometido', 'R$ 1.350,00', 'text-amber-600']].map(([label, value, color]) => <div className="rounded-xl border border-slate-100 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950" key={label}><p className="text-xs font-medium text-slate-500 dark:text-slate-400">{label}</p><p className={`mt-2 text-lg font-bold ${color}`}>{value}</p></div>)}
    </div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[1.5fr_1fr]">
      <div className="rounded-xl border border-slate-100 p-4 dark:border-slate-800"><div className="flex items-center justify-between"><p className="font-semibold text-slate-900 dark:text-white">Evolução do saldo</p><TrendingUp className="text-cyan-600" size={18} /></div><div className="mt-7 flex h-36 items-end gap-2">{[44, 56, 48, 73, 62, 81, 92].map((height, index) => <div className="group flex flex-1 flex-col justify-end" key={height}><div className="rounded-t-sm bg-gradient-to-t from-cyan-600 to-sky-300 transition-transform duration-300 group-hover:-translate-y-1" style={{ height: `${height}%` }} /><span className="mt-2 text-center text-[10px] text-slate-400">{['S', 'T', 'Q', 'Q', 'S', 'S', 'D'][index]}</span></div>)}</div></div>
      <div className="rounded-xl bg-slate-950 p-4 text-white"><p className="text-sm font-semibold">Livre para utilizar</p><p className="mt-3 text-2xl font-bold text-cyan-300">R$ 1.440,00</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-700"><div className="h-full w-[58%] rounded-full bg-cyan-400" /></div><p className="mt-3 text-xs leading-5 text-slate-300">Depois dos seus compromissos já previstos.</p></div>
    </div>
    <div className="mt-4 rounded-xl border border-slate-100 p-4 dark:border-slate-800"><div className="flex items-center justify-between"><div><p className="font-semibold text-slate-900 dark:text-white">Nubank</p><p className="mt-1 text-sm text-slate-500">R$ 1.240 / R$ 4.000</p></div><CreditCard className="text-cyan-600" size={24} /></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full w-[31%] rounded-full bg-cyan-500" /></div><div className="mt-3 flex justify-between text-xs text-slate-500"><span>31% utilizado</span><span>Fecha dia 05 · Vence dia 12</span></div></div>
  </motion.div>;
}

export function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [projectionMonths, setProjectionMonths] = useState(6);
  return <main className="overflow-x-hidden bg-[#f7fbfc] text-slate-950 dark:bg-slate-950 dark:text-slate-100">
    <header className="sticky top-0 z-50 border-b border-slate-200/70 bg-[#f7fbfc]/85 backdrop-blur-xl dark:border-slate-800 dark:bg-slate-950/85"><div className="mx-auto flex min-h-20 max-w-7xl items-center justify-between px-4 sm:px-6"><Link aria-label="Nuvexa: página inicial" className="rounded-md bg-white px-2 py-1 shadow-sm" to="/"><img alt="Nuvexa" className="h-8 w-auto sm:h-9" src={logo} /></Link><nav className="hidden items-center gap-6 text-sm font-semibold text-slate-600 lg:flex dark:text-slate-300"><a href="#inicio">Início</a><a href="#como-funciona">Como funciona</a><a href="#recursos">Recursos</a><a href="#ia">Nuvexa IA</a><a href="#seguranca">Segurança</a><a href="#planos">Planos</a></nav><div className="hidden items-center gap-3 sm:flex"><ThemeToggle /><Link className="rounded-lg px-3 py-2 text-sm font-bold text-slate-700 hover:text-cyan-700 dark:text-slate-200" to="/login">Entrar</Link><Link className="rounded-lg bg-slate-950 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-cyan-900/15 transition hover:-translate-y-0.5 hover:bg-cyan-700 dark:bg-cyan-500 dark:text-slate-950" to="/login">Criar conta grátis</Link></div><button aria-label="Abrir menu" className="rounded-lg p-2 lg:hidden" onClick={() => setMenuOpen(!menuOpen)} type="button">{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen ? <nav className="grid gap-1 border-t border-slate-200 px-4 py-4 text-sm font-semibold lg:hidden dark:border-slate-800">{[['Início', '#inicio'], ['Como funciona', '#como-funciona'], ['Recursos', '#recursos'], ['Nuvexa IA', '#ia'], ['Segurança', '#seguranca'], ['Planos', '#planos']].map(([label, target]) => <a className="rounded-md px-3 py-3 hover:bg-white dark:hover:bg-slate-900" href={target} key={label} onClick={() => setMenuOpen(false)}>{label}</a>)}<Link className="mt-2 rounded-lg bg-slate-950 px-4 py-3 text-center text-white dark:bg-cyan-400 dark:text-slate-950" to="/login">Criar conta grátis</Link></nav> : null}</header>

    <Section className="relative pb-10 pt-16 sm:pt-24 lg:pt-28" id="inicio"><div className="absolute left-1/2 top-0 -z-0 h-[430px] w-[720px] -translate-x-1/2 rounded-full bg-cyan-200/30 blur-3xl dark:bg-cyan-500/10" /><div className="relative grid items-center gap-14 lg:grid-cols-[0.9fr_1.1fr]"><motion.div initial="hidden" transition={{ duration: 0.55 }} variants={reveal} viewport={{ once: true }} whileInView="visible"><div className="inline-flex items-center gap-2 rounded-full border border-cyan-200 bg-white/80 px-3 py-2 text-sm font-bold text-cyan-800 shadow-sm dark:border-cyan-400/30 dark:bg-slate-900 dark:text-cyan-200"><Sparkles size={16} /> Inteligência financeira para sua vida</div><h1 className="mt-7 text-4xl font-black leading-[1.04] sm:text-5xl lg:text-6xl">Entenda para onde seu dinheiro vai.<span className="block mt-3 text-cyan-700 dark:text-cyan-300">E assuma o controle do que vem pela frente.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600 dark:text-slate-300">A Nuvexa organiza suas receitas, despesas, cartões, parcelas e compromissos futuros para mostrar sua vida financeira de forma simples, inteligente e visual.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg bg-slate-950 px-5 text-sm font-bold text-white shadow-lg shadow-slate-900/20 transition hover:-translate-y-0.5 hover:bg-cyan-700 dark:bg-cyan-400 dark:text-slate-950" to="/login">Começar gratuitamente <ArrowRight size={18} /></Link><a className="inline-flex min-h-12 items-center justify-center rounded-lg border border-slate-300 bg-white px-5 text-sm font-bold text-slate-800 transition hover:border-cyan-400 hover:text-cyan-700 dark:border-slate-700 dark:bg-slate-900 dark:text-white" href="#como-funciona">Ver como funciona</a></div><div className="mt-8 grid grid-cols-2 gap-x-4 gap-y-3 text-sm font-semibold text-slate-600 sm:grid-cols-4 dark:text-slate-300">{['Fácil de configurar', 'Seus dados protegidos', 'Controle completo', 'Inteligência financeira'].map(item => <span className="flex items-center gap-2" key={item}><Check className="text-cyan-600" size={16} />{item}</span>)}</div></motion.div><DemoDashboard /></div><motion.div className="relative mt-12 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-soft dark:border-slate-800 dark:bg-slate-900" initial="hidden" transition={{ duration: 0.5 }} variants={reveal} viewport={{ once: true }} whileInView="visible"><img alt="Nuvexa - Sua vida financeira, mais clara" className="block aspect-[2.66/1] w-full object-cover dark:hidden" src={bannerClaro} /><img alt="Nuvexa - Sua vida financeira, mais clara" className="hidden aspect-[2.66/1] w-full object-cover dark:block" src={bannerEscuro} /></motion.div></Section>

    <Section className="bg-white dark:bg-slate-900"><SectionHeading align="center" eyebrow="O problema" title="Seu salário entra. Mas você sabe para onde ele vai?" /><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{questions.map((question, index) => <motion.div className="rounded-xl border border-slate-100 bg-slate-50 p-5 text-base font-semibold text-slate-700 shadow-sm dark:border-slate-800 dark:bg-slate-950 dark:text-slate-200" initial="hidden" key={question} transition={{ delay: index * 0.04 }} variants={reveal} viewport={{ once: true }} whileInView="visible">{question}</motion.div>)}</div><p className="mt-10 text-center text-xl font-bold text-cyan-700 dark:text-cyan-300">A Nuvexa foi criada para responder essas perguntas.</p></Section>

    <Section id="como-funciona"><SectionHeading eyebrow="Como funciona" title="Organizar sua vida financeira pode ser simples." description="Uma rotina clara para enxergar o presente e planejar os próximos passos." /><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{steps.map(([number, title, description], index) => <motion.article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900" initial="hidden" key={number} transition={{ delay: index * 0.08 }} variants={reveal} viewport={{ once: true }} whileInView="visible"><p className="text-sm font-black tracking-[0.14em] text-cyan-700 dark:text-cyan-300">{number}</p><h3 className="mt-7 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">{description}</p></motion.article>)}</div></Section>

    <Section className="bg-slate-950 text-white" id="recursos"><div className="grid gap-12 lg:grid-cols-[0.9fr_1.1fr]"><div><SectionHeading eyebrow="Receitas e gastos" title="Saiba exatamente quanto você ganha." description="Salário, renda extra, investimentos, freelances, aluguéis e entradas avulsas em uma visão que faz sentido." /><div className="mt-8 grid grid-cols-2 gap-3 text-sm">{[['Salário', 'R$ 4.800'], ['Freelances', 'R$ 820'], ['Investimentos', 'R$ 310'], ['Renda extra', 'R$ 240']].map(([label, value]) => <div className="rounded-xl bg-white/10 p-4" key={label}><p className="text-slate-300">{label}</p><p className="mt-2 font-bold text-cyan-300">{value}</p></div>)}</div></div><div className="grid gap-4"><div className="rounded-2xl bg-white p-6 text-slate-950"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-500">Composição da renda</p><p className="mt-2 text-2xl font-black">R$ 6.170,00</p></div><PieChart className="text-cyan-600" size={30} /></div><div className="mt-7 flex h-8 overflow-hidden rounded-full"><div className="w-[78%] bg-cyan-500" /><div className="w-[14%] bg-sky-300" /><div className="w-[8%] bg-slate-300" /></div><div className="mt-3 flex gap-4 text-xs font-semibold text-slate-500"><span>Salário 78%</span><span>Freelance 14%</span><span>Outros 8%</span></div></div><div className="rounded-2xl border border-white/15 p-6"><p className="text-sm font-bold text-cyan-300">Nem todo gasto é igual.</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{[['Fixos', 'Aluguel, internet, academia'], ['Temporários', 'Curso de 8 meses', 'Restam 5 parcelas'], ['Esporádicos', 'Viagem para praia', 'R$ 1.330 no período']].map(([title, item, detail]) => <div className="rounded-lg bg-white/10 p-4" key={title}><p className="font-bold">{title}</p><p className="mt-2 text-sm text-slate-300">{item}</p>{detail ? <p className="mt-2 text-xs font-bold text-cyan-300">{detail}</p> : null}</div>)}</div></div></div></div></Section>

    <Section><div className="grid gap-12 lg:grid-cols-[1.05fr_0.95fr]"><div><SectionHeading eyebrow="Cartões" title="Todos os seus cartões. Sem surpresas na fatura." description="Acompanhe o limite, a fatura e cada parcela antes de tomar a próxima decisão." /><div className="mt-8 rounded-2xl bg-gradient-to-br from-cyan-600 via-sky-600 to-slate-900 p-6 text-white shadow-xl"><div className="flex justify-between"><span className="font-bold">Nubank</span><CreditCard /></div><p className="mt-12 text-2xl font-bold">R$ 1.240 <span className="text-base font-medium text-cyan-100">/ R$ 4.000</span></p><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/20"><div className="h-full w-[31%] rounded-full bg-white" /></div><div className="mt-4 flex justify-between text-sm text-cyan-100"><span>31% utilizado</span><span>Vence dia 12</span></div></div></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-soft dark:border-slate-800 dark:bg-slate-900"><p className="font-bold">Saiba quando você realmente vai pagar.</p><div className="mt-6 rounded-lg bg-cyan-50 p-4 text-sm text-cyan-950 dark:bg-cyan-400/10 dark:text-cyan-100"><p className="font-bold">Seu cartão fecha dia 05.</p><p className="mt-2">Compra realizada em <strong>06 de agosto</strong></p><p className="mt-3 font-bold">Essa compra será cobrada somente na próxima fatura.</p></div><div className="mt-7 flex items-center justify-between gap-2 text-center text-xs font-bold text-slate-500"><span>COMPRA</span><ArrowRight size={14} /><span>FECHAMENTO</span><ArrowRight size={14} /><span>FATURA</span><ArrowRight size={14} /><span>VENCIMENTO</span></div></div></div></Section>

    <Section className="bg-white dark:bg-slate-900"><div className="grid gap-12 lg:grid-cols-[0.9fr_1.1fr]"><div><SectionHeading eyebrow="Dinheiro disponível" title="Seu saldo não é necessariamente seu dinheiro disponível." description="A Nuvexa considera compromissos futuros antes de mostrar quanto você pode gastar com tranquilidade." /></div><div className="rounded-2xl border border-slate-200 p-6 shadow-soft dark:border-slate-800"><div className="grid gap-3 text-sm">{[['Salário', 'R$ 5.000', 'text-emerald-600'], ['Contas fixas', '- R$ 1.600', 'text-rose-600'], ['Cartões', '- R$ 900', 'text-rose-600'], ['Parcelamentos', '- R$ 600', 'text-rose-600'], ['Reserva planejada', '- R$ 500', 'text-rose-600']].map(([label, value, color]) => <div className="flex justify-between border-b border-slate-100 py-3 dark:border-slate-800" key={label}><span className="text-slate-500">{label}</span><strong className={color}>{value}</strong></div>)}</div><div className="mt-5 rounded-xl bg-slate-950 p-5 text-white"><p className="text-sm text-slate-300">Realmente disponíveis</p><p className="mt-1 text-3xl font-black text-cyan-300">R$ 1.400</p></div></div></div></Section>

    <Section><SectionHeading eyebrow="Planejamento" title="Veja seu mês antes que ele aconteça." description="Calendário e projeções organizam entradas, contas, cartões, investimentos e parcelas no mesmo lugar." /><div className="mt-10 grid gap-5 lg:grid-cols-[1.1fr_0.9fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="mb-5 flex items-center justify-between"><p className="font-bold">Agosto 2026</p><CalendarDays className="text-cyan-600" /></div><div className="grid grid-cols-7 gap-2 text-center text-xs">{Array.from({ length: 28 }, (_, index) => <button className={`aspect-square rounded-lg border text-slate-500 transition hover:border-cyan-400 hover:bg-cyan-50 dark:border-slate-800 dark:hover:bg-slate-800 ${[5, 12, 18, 24].includes(index) ? 'border-cyan-200 bg-cyan-50 text-cyan-700 dark:bg-cyan-400/10 dark:text-cyan-200' : ''}`} key={index} type="button">{index + 1}</button>)}</div><div className="mt-5 flex flex-wrap gap-3 text-xs font-semibold"><span className="text-emerald-600">● Entrada</span><span className="text-rose-600">● Conta a pagar</span><span className="text-violet-600">● Cartão</span><span className="text-cyan-600">● Investimento</span><span className="text-amber-600">● Parcela</span></div></div><div className="rounded-2xl bg-slate-950 p-6 text-white"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-cyan-300">Projeção financeira</p><p className="mt-2 text-2xl font-bold">Próximos meses</p></div><BarChart3 className="text-cyan-300" /></div><div className="mt-6 flex gap-2">{[3, 6, 12].map(months => <button className={`rounded-md px-3 py-2 text-sm font-bold ${projectionMonths === months ? 'bg-cyan-400 text-slate-950' : 'bg-white/10 text-slate-200'}`} key={months} onClick={() => setProjectionMonths(months)} type="button">{months} meses</button>)}</div><div className="mt-7 flex h-28 items-end gap-3">{['Ago', 'Set', 'Out', 'Nov', 'Dez', 'Jan'].slice(0, projectionMonths === 3 ? 3 : 6).map((month, index) => <div className="flex flex-1 flex-col items-center gap-2" key={month}><div className="w-full rounded-t bg-cyan-400" style={{ height: `${45 + index * 8}%` }} /><span className="text-xs text-slate-300">{month}</span></div>)}</div><p className="mt-6 text-sm text-slate-300">Receitas, despesas, parcelamentos e saldo projetado em uma leitura simples.</p></div></div></Section>

    <Section className="bg-gradient-to-br from-cyan-50 via-white to-slate-100 dark:from-slate-900 dark:via-slate-950 dark:to-cyan-950/30" id="ia"><div className="grid gap-12 lg:grid-cols-[0.85fr_1.15fr]"><div><SectionHeading eyebrow="Nuvexa IA" title="Conheça a Nuvexa IA" description="Uma inteligência financeira que transforma seus números em respostas simples." /><div className="mt-7 grid gap-3 text-sm font-semibold text-slate-600 dark:text-slate-300">{['Quanto gastei com alimentação?', 'Qual cartão estou usando mais?', 'Por que estou gastando mais esse mês?', 'Quanto posso guardar?'].map(question => <div className="flex items-center gap-3" key={question}><BrainCircuit className="text-cyan-600" size={18} />{question}</div>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3 border-b border-slate-100 pb-4 dark:border-slate-800"><div className="rounded-lg bg-cyan-100 p-2 text-cyan-700 dark:bg-cyan-400/15 dark:text-cyan-200"><Bot size={20} /></div><div><p className="font-bold">Nuvexa IA</p><p className="text-xs text-emerald-600">Online agora</p></div></div><div className="mt-6 max-w-[80%] rounded-2xl rounded-bl-md bg-slate-100 p-4 text-sm leading-6 text-slate-700 dark:bg-slate-800 dark:text-slate-100">Posso gastar R$ 800 em um celular esse mês?</div><div className="mt-4 ml-auto max-w-[90%] rounded-2xl rounded-br-md bg-cyan-600 p-4 text-sm leading-6 text-white">Você pode realizar essa compra, mas seu dinheiro livre cairá de R$ 1.440 para R$ 640.<br /><br />Além disso, você possui R$ 520 em compromissos previstos antes do próximo salário.<br /><br /><strong>Minha recomendação é parcelar ou aguardar o próximo recebimento.</strong></div></div></div></Section>

    <Section><div className="grid gap-6 lg:grid-cols-3"><motion.article className="rounded-2xl bg-slate-950 p-7 text-white" initial="hidden" variants={reveal} viewport={{ once: true }} whileInView="visible"><p className="text-sm font-bold text-cyan-300">Nuvexa Score</p><p className="mt-6 text-7xl font-black">78</p><p className="mt-2 text-xl font-bold">Boa saúde financeira</p><p className="mt-4 leading-7 text-slate-300">Acompanhamento de compromissos, cartões, dívidas, reserva e capacidade de poupar.</p></motion.article><motion.article className="rounded-2xl border border-slate-200 bg-white p-7 dark:border-slate-800 dark:bg-slate-900" initial="hidden" transition={{ delay: 0.08 }} variants={reveal} viewport={{ once: true }} whileInView="visible"><TrendingUp className="text-rose-600" /><p className="mt-6 text-3xl font-black">↑ 23%</p><p className="mt-2 font-semibold">Você gastou 23% mais com alimentação neste mês.</p></motion.article><motion.article className="rounded-2xl border border-slate-200 bg-white p-7 dark:border-slate-800 dark:bg-slate-900" initial="hidden" transition={{ delay: 0.16 }} variants={reveal} viewport={{ once: true }} whileInView="visible"><Target className="text-cyan-600" /><p className="mt-6 text-3xl font-black">R$ 620</p><p className="mt-2 font-semibold">Se mantiver seu ritmo atual, poderá guardar aproximadamente este valor no mês.</p></motion.article></div><div className="mt-14 grid gap-10 lg:grid-cols-[0.9fr_1.1fr]"><div><SectionHeading eyebrow="Metas" title="Transforme dinheiro em objetivos." description="Planeje a reserva, uma viagem, a entrada da casa ou aquilo que importa para você." /></div><div className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><div><p className="font-bold">Computador novo</p><p className="mt-1 text-sm text-slate-500">R$ 3.400 / R$ 6.000</p></div><Target className="text-cyan-600" /></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full w-[57%] rounded-full bg-gradient-to-r from-cyan-500 to-sky-400" /></div><div className="mt-3 flex justify-between text-sm"><strong className="text-cyan-700 dark:text-cyan-300">57% concluído</strong><span className="text-slate-500">Fevereiro de 2027</span></div></div></div></Section>

    <Section className="bg-slate-950 text-white" id="seguranca"><SectionHeading align="center" eyebrow="Segurança" title="Seus dados financeiros são seus." description="A Nuvexa foi criada para organizar sua informação, nunca para movimentar o seu dinheiro." /><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{securityFeatures.map(({ icon: Icon, title, copy }) => <div className="rounded-xl border border-white/10 bg-white/5 p-6" key={title}><Icon className="text-cyan-300" size={24} /><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{copy}</p></div>)}</div></Section>

    <Section id="planos"><SectionHeading align="center" eyebrow="Planos" title="Comece no seu ritmo. Evolua quando quiser." description="Estrutura simples, sem preços definidos agora e pronta para acompanhar sua rotina." /><div className="mt-12 grid gap-5 lg:grid-cols-3">{plans.map(({ name, description, features }, index) => <div className={`relative rounded-2xl border p-7 ${index === 1 ? 'border-cyan-500 bg-slate-950 text-white shadow-xl shadow-cyan-900/15' : 'border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900'}`} key={name}>{index === 1 ? <span className="absolute -top-3 left-6 rounded-full bg-cyan-400 px-3 py-1 text-xs font-black text-slate-950">MAIS POPULAR</span> : null}<h3 className="text-2xl font-bold">{name}</h3><p className={`mt-3 min-h-12 text-sm leading-6 ${index === 1 ? 'text-slate-300' : 'text-slate-600 dark:text-slate-300'}`}>{description}</p><ul className="mt-7 grid gap-3 text-sm">{features.map(feature => <li className="flex items-center gap-2" key={feature}><Check className="text-cyan-500" size={17} />{feature}</li>)}</ul><Link className={`mt-8 inline-flex min-h-11 w-full items-center justify-center rounded-lg text-sm font-bold transition hover:-translate-y-0.5 ${index === 1 ? 'bg-cyan-400 text-slate-950' : 'bg-slate-950 text-white dark:bg-white dark:text-slate-950'}`} to="/login">Começar agora</Link></div>)}</div></Section>

    <Section className="bg-white dark:bg-slate-900"><SectionHeading align="center" eyebrow="Dúvidas comuns" title="Perguntas que aparecem antes de começar." /><div className="mx-auto mt-10 max-w-3xl divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white dark:divide-slate-800 dark:border-slate-800 dark:bg-slate-950">{faqs.map(([question, answer], index) => <div key={question}><button aria-expanded={openFaq === index} className="flex w-full items-center justify-between gap-4 px-5 py-5 text-left font-bold" onClick={() => setOpenFaq(openFaq === index ? null : index)} type="button"><span>{question}</span><ChevronDown className={`shrink-0 text-cyan-600 transition-transform ${openFaq === index ? 'rotate-180' : ''}`} size={20} /></button>{openFaq === index ? <div className="px-5 pb-5 text-sm leading-7 text-slate-600 dark:text-slate-300">{answer}</div> : null}</div>)}</div></Section>

    <Section className="pb-24"><div className="rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-cyan-900 px-6 py-16 text-center text-white sm:px-12"><p className="text-sm font-bold uppercase tracking-[0.16em] text-cyan-300">Comece hoje</p><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-black sm:text-5xl">Comece a entender seu dinheiro.</h2><p className="mt-5 text-lg text-slate-300">Organize hoje. Planeje amanhã. Conquiste mais.</p><Link className="mt-9 inline-flex min-h-12 items-center gap-2 rounded-lg bg-cyan-400 px-6 text-sm font-black text-slate-950 shadow-lg transition hover:-translate-y-0.5 hover:bg-cyan-300" to="/login">Criar minha conta <ArrowRight size={18} /></Link><p className="mt-4 text-sm text-slate-400">Comece gratuitamente.</p></div></Section>

    <footer className="border-t border-slate-200 bg-white px-4 py-12 dark:border-slate-800 dark:bg-slate-950"><div className="mx-auto grid max-w-7xl gap-10 sm:grid-cols-2 lg:grid-cols-[1.4fr_1fr_1fr_1fr_1fr]"><div><div className="inline-flex rounded-md bg-white p-2"><img alt="Nuvexa" className="h-10 w-auto" src={logo} /></div><p className="mt-4 max-w-xs text-sm leading-6 text-slate-500">Inteligência para uma vida financeira melhor.</p></div>{[['Produto', ['Recursos', 'Nuvexa IA', 'Planos', 'Atualizações']], ['Empresa', ['Sobre', 'Contato', 'Ajuda']], ['Segurança', ['Privacidade', 'LGPD', 'Segurança', 'Termos de uso']], ['Redes sociais', ['Instagram', 'LinkedIn', 'YouTube']]].map(([title, links]) => <div key={title as string}><p className="font-bold">{title as string}</p><div className="mt-4 grid gap-3 text-sm text-slate-500">{(links as string[]).map(link => <a className="hover:text-cyan-700 dark:hover:text-cyan-300" href={link === 'Privacidade' ? '/privacy' : '#inicio'} key={link}>{link}</a>)}</div></div>)}</div><p className="mx-auto mt-12 max-w-7xl border-t border-slate-100 pt-6 text-sm text-slate-500 dark:border-slate-800">© 2026 Nuvexa. Todos os direitos reservados.</p></footer>
  </main>;
}