import { CreditCard } from "lucide-react";
import { formatCurrency } from "../lib/formatters";
import type { CreditCard as Card, Invoice } from "../types/creditCards";
import type { Transaction } from "../types/transactions";

export function CreditCardsSummary({ creditCards, invoices, transactions }: { creditCards: Card[]; invoices: Invoice[]; transactions: Transaction[] }) {
  const unpaid = new Set(invoices.filter((invoice) => invoice.status !== "paid").map((invoice) => invoice.id));
  const usages = creditCards.filter((card) => card.status === "active").map((card) => ({ card, used: transactions.filter((transaction) => transaction.credit_card_id === card.id && transaction.invoice_id && unpaid.has(transaction.invoice_id)).reduce((sum, transaction) => sum + transaction.amount, 0) }));
  const total = usages.reduce((sum, item) => sum + item.used, 0);
  return <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><div className="rounded-md bg-brand-50 p-2 text-brand-600 dark:bg-brand-600/15 dark:text-brand-100"><CreditCard aria-hidden="true" size={22} /></div><div><h2 className="text-sm font-medium text-slate-500 dark:text-slate-400">Limite total utilizado</h2><p className="mt-1 text-2xl font-bold text-slate-950 dark:text-white">{formatCurrency(total)}</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{usages.map(({ card, used }) => { const ratio = Math.min(100, (used / card.credit_limit) * 100); return <div className="rounded-md border border-slate-200 p-3 dark:border-slate-800" key={card.id}><div className="flex justify-between gap-2 text-sm"><span className="font-medium text-slate-950 dark:text-white">{card.name}</span><span className={ratio >= 80 ? "font-semibold text-negative-600 dark:text-negative-100" : "text-slate-500 dark:text-slate-400"}>{ratio.toFixed(0)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className={ratio >= 80 ? "h-full bg-negative-600" : "h-full bg-brand-600"} style={{ width: `${ratio}%` }} /></div><p className="mt-2 text-xs text-slate-500 dark:text-slate-400">{formatCurrency(used)} de {formatCurrency(card.credit_limit)}</p>{ratio >= 80 ? <p className="mt-1 text-xs font-medium text-negative-600 dark:text-negative-100">Uso acima de 80% do limite.</p> : null}</div>; })}</div></section>;
}